esphome:
  name: pir_cam
  platform: ESP32
  board: esp32dev

wifi:
  ssid: ""
  password: ""


logger:


api:
  password: ""

ota:
  password: ""

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 640x480
  jpeg_quality: 20


  name: PirCamera


output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4


